"""The generated corpus schema (spec section 12).

``SCHEMA.md`` is emitted from the same constants the writer validates against and
the reader pins, so it cannot drift from the data. It is the file an agent reads
before touching anything.
"""

from pathlib import Path

from logmint._identity import RESERVED, RUN_ID_CHARS
from logmint._read import CORE

_QUERIES = [
    (
        "Every finished run and its config",
        (
            "SELECT * FROM runs WHERE run IN (SELECT run FROM events "
            "WHERE kind='status' AND status='finished');"
        ),
    ),
    (
        "One metric across seeds, ready for a figure",
        (
            "SELECT method, step, avg(value) AS y, stddev_samp(value)/sqrt(count(*)) "
            "AS yerr, count(*) AS n FROM metrics WHERE name='acc' AND split='forget' "
            "GROUP BY method, step ORDER BY method, step;"
        ),
    ),
    (
        "How many finished seeds exist per config, which is what gates an error bar",
        (
            "SELECT * EXCLUDE (seed, run), count(*) AS seeds FROM runs "
            "GROUP BY ALL ORDER BY seeds;"
        ),
    ),
    (
        "Runs that diverged",
        "SELECT DISTINCT run, name FROM events WHERE nonfinite IS NOT NULL;",
    ),
    (
        "Every blob a run produced",
        "SELECT run, step, name, ref FROM events WHERE kind='blob' ORDER BY run, step;",
    ),
]


def render() -> str:
    """Render the corpus schema.

    Returns:
        The text of ``SCHEMA.md``.

    """
    core = "\n".join(f"| `{k}` | `{v}` |" for k, v in CORE.items())
    reserved = ", ".join(f"`{k}`" for k in sorted(RESERVED))
    queries = "\n\n".join(f"{title}:\n\n```sql\n{sql}\n```" for title, sql in _QUERIES)
    return f"""# Corpus schema

Generated by `logmint schema`. Everything here except `blobs/` is UTF-8 text at a
predictable path, so `head -3` is enough to learn the format and `grep` is enough
to find a number.

## Layout

```
runs/<run_id>/run.json           the config, and nothing else. written once
runs/<run_id>/events.<NN>.jsonl  one JSON object per line. one file per attempt
runs/<run_id>/log.<NN>.txt       the stderr tee. no parser reads this
blobs/<h0h1>/<rest>              every non-scalar, named by the sha256 of its bytes
```

`run_id` is the first {RUN_ID_CHARS} hex characters of the sha256 of the
canonical `run.json`, so `sha256(canonical(run.json))[:{RUN_ID_CHARS}] ==
basename(dir)` always holds. A config is flat and its keys are identifiers,
because every key becomes a column of the read frame. They may not be named
{reserved}, which are columns already, and a coordinate may not take the name of
a config key, because the frame is the join of the two.

## Records

Every line of an event stream is a JSON object with a `kind`:

- `start` - opens an attempt. Carries the commit, the dirty-diff hash, the
  lockfile hash, the host, the GPUs, the scheduler job id, and the step this
  attempt resumed from.
- `metric` - one scalar result. `name` and `value` are required; `step` and
  `split` are optional; **every other key is a coordinate** (`t`, `layer`,
  `eigen_index`, ...). Records are ragged by design: a new coordinate is a new
  key on new lines, and every earlier file still reads.
- `blob` - an output blob. Carries `ref`, `format`, and metadata such as `shape`
  and `dtype`.
- `event` - a runtime fact worth querying, so the text log never has to carry results.
- `status` - terminal, at most one per attempt, always the last line: `finished`
  or `failed`. It declares `coords`, the coordinate names the attempt used and
  their types, which is how the reader learns the schema from a tail read instead
  of a scan of every line.

## Views

`logmint query` and `logmint.query` define three views over the corpus.

- `metrics` - the tidy frame: one row per metric record, config columns joined on,
  deduplicated across attempts (highest attempt wins). This is what a figure is
  made from.
- `runs` - one row per run: `run` plus every config key.
- `events` - every record of every kind, with every field: the provenance on a
  `start`, the fields on an `event`, the shape and dtype on a `blob`. Ask this one
  anything the tidy frame drops.

A non-finite value is written as `"value": null` with a `nonfinite` tag of `nan`,
`+inf` or `-inf`. RFC 8259 has no `NaN` token, so writing one would produce a line
only some parsers read.

### Pinned columns

| column | type |
| --- | --- |
{core}

Coordinates are discovered from the corpus and pinned alongside these.

## Reading

A run's frame is the concatenation of its attempt files in index order, minus
lines that do not parse (at most one per file, always the last), deduplicated on
`(name, step, split, coordinates)` keeping the **highest attempt**. A run is
complete iff some attempt recorded `finished`; incomplete runs are excluded and
counted.

```python
import logmint
frame = logmint.load("<root>", names=["acc"]).filter(split="forget")
table = logmint.aggregate(frame, over="seed", x="step", by=["method"])
```

`aggregate` returns `y`, `yerr` = s/sqrt(n), and `n`. It raises rather than return
a wrong error bar: if a `(by, x, over)` group holds more than one row the frame
carries a dimension you have not named; if a value diverged it would be skipped by
the mean but still counted by `n`; if `n` varies along `x` the band is not
comparable from point to point.

## Queries

The `logmint query` command defines three views: `events` (every record), `runs`
(every config), and `metrics` (metric records, deduplicated, joined to the config,
finished runs only).

{queries}

## Blobs

A blob is referenced exactly one way, as the string `blob:<sha256>`, from a value
in a `run.json` (an input, which is therefore part of the run's identity) or from
a `blob` record (an output). The reachable set needs no parser:

```sh
grep -rhoE 'blob:[0-9a-f]{{64}}' runs/ | sort -u
```
"""


def write(root: Path | str) -> Path:
    """Write ``SCHEMA.md`` into a corpus.

    Args:
        root: The corpus root.

    Returns:
        The path written.

    """
    path = Path(root) / "SCHEMA.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")
    return path
